version: '3.8'
services:  
  db:  
    image: mysql:5.7
    restart: always
    environment:  
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
  redis:  
    image: redis:7.0.5
    restart: always
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/chatsystem'
    environment:
      REDIS_URL_SIDEKIQ : 'redis://redis:6379/1'
  elasticsearch:
    image: elasticsearch:7.17.1
    restart: always
    environment:
      - cluster.name=cluster_name
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - http.port = 9200
      - transport.host=0.0.0.0
      - discovery.type=single-node
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  app:
    build: .
    command: sh -c 'sh ./init.sh && rails s -p 3000 -b '0.0.0.0''
    restart: always
    volumes:
        - ".:/chatsystem"
    ports:  
      - "3000:3000"
    depends_on:  
      - db
      - redis
    links:
      - db
      - redis
    environment :
      DB_USER: root
      DB_NAME: noteapp
      DB_PASSWORD: password
      DB_HOST: db
      REDIS_URL_SIDEKIQ : 'redis://redis:6379/1'
      ELASTIC_HOST: elasticsearch
      ELASTIC_PORT: 9200
      
volumes:
  redis: